apiVersion: mcad.codeflare.dev/v1beta1
kind: ClusterInfo
metadata:
  labels:
    app.kubernetes.io/name: clusterinfo
    app.kubernetes.io/instance: clusterinfo-sample
    app.kubernetes.io/part-of: mcad
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mcad
  name: clusterinfo-sample
spec:
  # TODO(user): Add fields here
