---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.0
  name: appwrappers.workload.codeflare.dev
spec:
  group: workload.codeflare.dev
  names:
    kind: AppWrapper
    listKind: AppWrapperList
    plural: appwrappers
    singular: appwrapper
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.state
      name: Status
      type: string
    - jsonPath: .status.restarts
      name: Restarts
      type: integer
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: AppWrapper is the Schema for the appwrappers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AppWrapperSpec defines the desired state of AppWrapper
            properties:
              priority:
                description: Priority
                format: int32
                type: integer
              priorityslope:
                anyOf:
                - type: integer
                - type: string
                description: Priority slope
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              resources:
                description: Wrapped resources
                properties:
                  GenericItems:
                    description: Array of GenericItems
                    items:
                      description: AppWrapper resource
                      properties:
                        completionstatus:
                          description: A comma-separated list of keywords to match
                            against condition types
                          type: string
                        custompodresources:
                          description: Array of resource requests
                          items:
                            description: Resource requests
                            properties:
                              limits:
                                additionalProperties:
                                  anyOf:
                                  - type: integer
                                  - type: string
                                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                  x-kubernetes-int-or-string: true
                                description: Limits per replica
                                type: object
                              replicas:
                                description: Replica count
                                format: int32
                                type: integer
                              requests:
                                additionalProperties:
                                  anyOf:
                                  - type: integer
                                  - type: string
                                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                  x-kubernetes-int-or-string: true
                                description: Resource requests per replica
                                type: object
                            required:
                            - replicas
                            - requests
                            type: object
                          type: array
                        generictemplate:
                          description: Resource template
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        replicas:
                          format: int32
                          type: integer
                      required:
                      - generictemplate
                      type: object
                    type: array
                required:
                - GenericItems
                type: object
              schedulingSpec:
                description: Scheduling specification
                properties:
                  forceDeletionTimeInSeconds:
                    description: Enable forced deletion after delay if nonzero
                    format: int64
                    type: integer
                  minAvailable:
                    description: Minimum number of expected running and successful
                      pods
                    format: int32
                    type: integer
                  requeuing:
                    description: Requeuing specification
                    properties:
                      maxNumRequeuings:
                        description: Max requeuings permitted (infinite if zero)
                        format: int32
                        type: integer
                      pauseTimeInSeconds:
                        description: Wait time before trying to dispatch again after
                          requeuing
                        format: int64
                        type: integer
                      timeInSeconds:
                        default: 300
                        description: Initial waiting time before requeuing conditions
                          are checked
                        format: int64
                        type: integer
                    type: object
                type: object
            required:
            - resources
            type: object
          status:
            description: AppWrapperStatus defines the observed state of AppWrapper
            properties:
              dispatchTimestamp:
                description: When last dispatched
                format: date-time
                type: string
              requeueTimestamp:
                description: When last requeued
                format: date-time
                type: string
              restarts:
                description: How many times restarted
                format: int32
                type: integer
              state:
                description: Phase
                type: string
              step:
                description: Status of wrapped resources
                type: string
              transitions:
                description: Transition log
                items:
                  description: Phase transition
                  properties:
                    reason:
                      description: Reason
                      type: string
                    state:
                      description: Phase entered
                      type: string
                    step:
                      description: Status of wrapped resources
                      type: string
                    time:
                      description: Timestamp
                      format: date-time
                      type: string
                  required:
                  - state
                  - time
                  type: object
                type: array
            required:
            - restarts
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
